apiVersion: v1
kind: Pod
metadata:
  name: flask-webapp
  labels:
    tier: front-end
spec:
  containers:
  - name: flask-container
    image: localhost:5000/tejarat_flask_app
    imagePullPolicy: IfNotPresent 
    ports:
    - containerPort: 8080
