apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    tier: front-end
spec:
  type: NodePort
  selector: 
    tier: front-end
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008

