FROM python:3.9-slim

WORKDIR /app

COPY app_northwind.py /app/
COPY templates /app/templates

RUN pip install --no-cache-dir flask psycopg2-binary sqlalchemy 

EXPOSE 5000

CMD ["python","app_northwind.py"]

