FROM node:18-slim

RUN apt-get update && \
    apt-get install -y curl wget && \
    apt-get install -y redis-tools && \
    apt-get clean

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install axios

COPY server.js ./

EXPOSE 3001

CMD ["node","server.js"]

