apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-app-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kube-app-data/python-app
  persistentVolumeReclaimPolicy: Retain
