apiVersion: v1
kind: Service
metadata:
  name: flaks-service-nodeport
spec:
  type: NodePort
  selector: 
    app: frn-flask-app-v1
  ports:
    - port: 3000
      targetPort: 5000
      nodePort: 30080




